# Generated by Django 5.0.1 on 2024-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_migration', '0002_airport_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=20)),
                ('flights', models.ManyToManyField(blank=True, related_name='Passengers', to='sql_migration.flight')),
            ],
        ),
    ]
